### ISSUE TITLE
Now working with Next.js 13

### ISSUE THREAD

**Issue by ziaukhan** [seveibar/kysely-neon#1]
It is not working with Next.js 13, I have documented it here:

https://github.com/panaverse/learn-nextjs/tree/main/step12_serverless_databases/relational/step01_typed_sql

**Comment by ziaukhan** [comment]
I have already installed ws as you may see in the package.json file. I have installed it by giving the following command:
      npm installed ws
but it is still not working. I don't understand what you mean by peer dependency?

**Comment by ziaukhan** [comment]
I have also documented the error here:
https://github.com/panaverse/learn-nextjs/tree/main/step12_serverless_databases/relational/step01_typed_sql#note-i-am-getting-the-following-error

**Comment by ziaukhan** [comment]
I have got Next.js 13, Neon, and Kysely working with PostgresDialect:
https://github.com/panaverse/learn-nextjs/tree/main/step12_serverless_databases/relational/step01b_typed_sql_working
However still not able to run with Neon Dialect:
https://github.com/panaverse/learn-nextjs/tree/main/step12_serverless_databases/relational/step01_typed_sql

**Comment by codewithcheese** [comment]
@ziaukhan all your URLs are 404 so this issue is now not helpful for anyone. Please write you issues and solutions rather than linking in the future.

**Comment by ProMBZ** [comment]
good
