### ISSUE TITLE
Error: Do not know how to serialize a BigInt

### ISSUE THREAD

**Issue by shakibhasan09** [seveibar/kysely-neon#12]
Hi, I'm using kysel ^0.261 and kysely-neon^1.3.0 and I have a query like that await db.deleteFrom("forms").where("id", "=", form_id).execute() //form_id is a number;   but it returning an error when I run that query.

Form table types:
export type forms = {
    id: Generated<number>;
    user_id: number;
    title: string;
    type: Generated<form_type>;
    action_id: number | null;
    created_at: Generated<Timestamp | null>;
    updated_at: Timestamp | null;
};

//db
import { Kysely } from "kysely";
import { DB } from "@/types/database";
import { NeonDialect } from "kysely-neon";

const db = new Kysely<DB>({
    dialect: new NeonDialect({
        connectionString: process.env.DATABASE_URL,
    }),
});

export default db;

**Comment by mackinleysmith** [comment]
This is also broken for the `NUMERIC` type. Were you able to find some solution?
