### ISSUE TITLE
Version 1.1.1 published to NPM without dist dir

### ISSUE THREAD

**Issue by sannajammeh** [seveibar/kysely-neon#5]
Version 1.1.1 is not runnable and causes projects to crash. It is not built upon deployment to NPM.
Only the src dir is present, whereas the exports field point to a `dist` directory which doesn't exist upon install.

Repro: Check npm code here:
https://www.npmjs.com/package/kysely-neon?activeTab=code

**Comment by bkniffler** [comment]
Yep, same issue here

**Comment by seveibar** [comment]
Fixing this, thanks and sorry everyone :)

**Comment by seveibar** [comment]
1.1.3 should have this fixed
